manifest:
  # defaults:
  #   revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: chiinthedesert
      url-base: https://github.com/chiinthedesert
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-led-indicator
      remote: chiinthedesert
      revision: main
  self:
    path: config
